apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: nodejs-app
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: tododb
  DB_USER: postgres
  PORT: "3000"
  NODE_ENV: production
